/**
 * src/lessons.js
 * Pure data module — no runtime logic.
 * Lesson definitions, topology templates, and incident scripts.
 * Extracted verbatim from NetWatch_V1.0.1.html.
 */

export const DEVICE_TYPES = {
  gateway:  { label: 'Gateway / Router',    icon: 'GW',  color: '#F59E0B' },
  web:      { label: 'Web / App Server',    icon: 'WEB', color: '#06B6D4' },
  database: { label: 'Database Server',     icon: 'DB',  color: '#A78BFA' },
  aicompute:{ label: 'AI / GPU Compute',    icon: 'GPU', color: '#22C55E' },
  client:   { label: 'Client Workstation',  icon: 'PC',  color: '#64748B' },
  switch:   { label: 'Switch',              icon: 'SW',  color: '#38BDF8' },
};

/* baseline "resting" telemetry per device type */
export const BASELINE = {
  gateway:  { cpu: 22, mem: 35, traffic: 60,  disk: 8,  temp: 38, gpu: 0,  vram: 0  },
  web:      { cpu: 28, mem: 44, traffic: 40,  disk: 15, temp: 40, gpu: 0,  vram: 0  },
  database: { cpu: 24, mem: 55, traffic: 18,  disk: 30, temp: 39, gpu: 0,  vram: 0  },
  aicompute:{ cpu: 30, mem: 40, traffic: 25,  disk: 20, temp: 52, gpu: 35, vram: 40 },
  client:   { cpu: 12, mem: 30, traffic: 4,   disk: 4,  temp: 34, gpu: 0,  vram: 0  },
  switch:   { cpu: 15, mem: 22, traffic: 80,  disk: 5,  temp: 35, gpu: 0,  vram: 0  },
};

/* ─────────────────────────── TOPOLOGY TEMPLATES ─────────────────────────── */
export const TOPOLOGIES = {
  branch_office: {
    name: 'Branch Office Network',
    nodes: [
      { id: 'isp',  label: 'ISP Uplink',   type: 'client',   x: 60,  y: 190, isExternal: true },
      { id: 'gw1',  label: 'GW-1',         type: 'gateway',  x: 220, y: 190 },
      { id: 'web1', label: 'SRV-WEB-1',    type: 'web',      x: 420, y: 90  },
      { id: 'db1',  label: 'SRV-DB-1',     type: 'database', x: 420, y: 290 },
      { id: 'wks1', label: 'WKS-01',       type: 'client',   x: 620, y: 40  },
      { id: 'wks2', label: 'WKS-02',       type: 'client',   x: 620, y: 140 },
      { id: 'wks3', label: 'WKS-03',       type: 'client',   x: 620, y: 340 },
    ],
    links: [
      { a: 'isp',  b: 'gw1'  },
      { a: 'gw1',  b: 'web1' },
      { a: 'gw1',  b: 'db1'  },
      { a: 'web1', b: 'db1'  },
      { a: 'web1', b: 'wks1' },
      { a: 'web1', b: 'wks2' },
      { a: 'db1',  b: 'wks3' },
    ],
  },
  ai_cluster: {
    name: 'AI Training Cluster',
    nodes: [
      { id: 'isp',   label: 'ISP Uplink',    type: 'client',    x: 60,  y: 190, isExternal: true },
      { id: 'gw1',   label: 'GW-1',          type: 'gateway',   x: 200, y: 190 },
      { id: 'sched', label: 'SRV-SCHED',     type: 'web',       x: 360, y: 190 },
      { id: 'gpu1',  label: 'GPU-NODE-01',   type: 'aicompute', x: 540, y: 80  },
      { id: 'gpu2',  label: 'GPU-NODE-02',   type: 'aicompute', x: 540, y: 190 },
      { id: 'gpu3',  label: 'GPU-NODE-03',   type: 'aicompute', x: 540, y: 300 },
      { id: 'store', label: 'SRV-STORAGE',   type: 'database',  x: 700, y: 190 },
    ],
    links: [
      { a: 'isp',   b: 'gw1'   },
      { a: 'gw1',   b: 'sched' },
      { a: 'sched', b: 'gpu1'  },
      { a: 'sched', b: 'gpu2'  },
      { a: 'sched', b: 'gpu3'  },
      { a: 'gpu1',  b: 'store' },
      { a: 'gpu2',  b: 'store' },
      { a: 'gpu3',  b: 'store' },
    ],
  },
  small_lan: {
    name: 'Small Office LAN',
    nodes: [
      { id: 'isp',  label: 'ISP Uplink',   type: 'client',  x: 60,  y: 190, isExternal: true },
      { id: 'gw1',  label: 'GW-1',         type: 'gateway', x: 210, y: 190 },
      { id: 'web1', label: 'SRV-WEB-1',    type: 'web',     x: 400, y: 90  },
      { id: 'sw1',  label: 'SW-1',         type: 'switch',  x: 400, y: 290 },
      { id: 'wks1', label: 'WKS-01',       type: 'client',  x: 610, y: 150 },
      { id: 'wks2', label: 'WKS-02',       type: 'client',  x: 610, y: 230 },
      { id: 'wks3', label: 'WKS-03',       type: 'client',  x: 610, y: 330 },
    ],
    links: [
      { a: 'isp',  b: 'gw1'  },
      { a: 'gw1',  b: 'web1' },
      { a: 'gw1',  b: 'sw1'  },
      { a: 'sw1',  b: 'wks1' },
      { a: 'sw1',  b: 'wks2' },
      { a: 'sw1',  b: 'wks3' },
    ],
  },
};

/* ─────────────────────────── INCIDENT SCRIPTS ─────────────────────────── */
export const INCIDENTS = {
  ddos_incident: {
    packetPattern: 'ddos',
    focusDevice: 'gw1',
    stages: [
      { atSecond: 0,  log: { level: 'info', text: 'Baseline monitoring active. All systems nominal.' } },
      { atSecond: 6,  targets: { gw1: { cpu: 58, traffic: 220 } },
        links: [{ a:'isp', b:'gw1', latency: 60, loss: 1.2 }],
        log: { level: 'warn', text: 'GW-1: inbound traffic climbing above baseline.' } },
      { atSecond: 14, targets: { gw1: { cpu: 95, traffic: 480, mem: 70 } },
        links: [{ a:'isp', b:'gw1', latency: 240, loss: 7.5 }],
        alert: { level: 'critical', device: 'gw1', title: 'GW-1: Abnormal inbound traffic flood', detail: 'Inbound packet rate is ~8x baseline from many distinct source addresses.' },
        log: { level: 'err', text: 'ALERT: GW-1 CPU 95% — uplink saturated, packet loss rising.' } },
      { atSecond: 26, targets: { web1: { cpu: 46, traffic: 20 } },
        alert: { level: 'warning', device: 'web1', title: 'SRV-WEB-1: reduced throughput', detail: 'Traffic reaching SRV-WEB-1 has dropped — likely starved behind the congested gateway.' },
        log: { level: 'warn', text: 'SRV-WEB-1: inbound traffic dropped, requests timing out.' } },
    ],
  },
  db_slowdown_incident: {
    packetPattern: 'dbslow',
    focusDevice: 'db1',
    stages: [
      { atSecond: 0,  log: { level: 'info', text: 'Baseline monitoring active. All systems nominal.' } },
      { atSecond: 7,  targets: { db1: { cpu: 55, disk: 60, mem: 66 } },
        log: { level: 'warn', text: 'SRV-DB-1: disk I/O pressure increasing.' } },
      { atSecond: 15, targets: { db1: { cpu: 92, disk: 96, mem: 88 } },
        alert: { level: 'critical', device: 'db1', title: 'SRV-DB-1: sustained high disk I/O + CPU', detail: 'A long-running query appears to be scanning large tables repeatedly, saturating disk I/O.' },
        log: { level: 'err', text: 'ALERT: SRV-DB-1 disk I/O at 96% — query latency spiking.' } },
      { atSecond: 24, targets: { web1: { cpu: 50 } },
        links: [{ a:'web1', b:'db1', latency: 180, loss: 0.4 }],
        alert: { level: 'warning', device: 'web1', title: 'SRV-WEB-1: elevated response times', detail: 'SRV-WEB-1 is waiting on slow database responses, causing request queues to build.' },
        log: { level: 'warn', text: 'SRV-WEB-1: DB query latency now above 150ms, requests queueing.' } },
    ],
  },
  gpu_thermal_incident: {
    packetPattern: 'gpu_net',
    focusDevice: 'gpu2',
    stages: [
      { atSecond: 0,  log: { level: 'info', text: 'Baseline monitoring active. All systems nominal.' } },
      { atSecond: 6,  targets: { gpu2: { gpu: 92, temp: 78, cpu: 60 } },
        log: { level: 'warn', text: 'GPU-NODE-02: utilization and temperature climbing during checkpoint sync.' } },
      { atSecond: 15, targets: { gpu2: { gpu: 99, temp: 94, cpu: 80, vram: 97 } },
        alert: { level: 'critical', device: 'gpu2', title: 'GPU-NODE-02: thermal threshold exceeded', detail: 'Sustained near-100% GPU utilization has pushed core temperature past safe limits; thermal throttling is likely.' },
        log: { level: 'err', text: 'ALERT: GPU-NODE-02 temp 94°C — thermal throttling engaged, clocks reduced.' } },
      { atSecond: 24, targets: { gpu2: { gpu: 55, cpu: 55 } },
        links: [{ a:'sched', b:'gpu2', latency: 90, loss: 3.5 }],
        alert: { level: 'warning', device: 'gpu2', title: 'GPU-NODE-02: degraded training throughput', detail: 'Throttling has cut effective compute throughput; job progress on this node has stalled relative to its peers.' },
        log: { level: 'warn', text: 'GPU-NODE-02: throughput dropped ~40% after throttle, sync traffic retrying.' } },
    ],
  },
  internal_overload_incident: {
    packetPattern: 'connflood',
    focusDevice: 'gw1',
    stages: [
      { atSecond: 0,  log: { level: 'info', text: 'Baseline monitoring active. All systems nominal.' } },
      { atSecond: 6,  targets: { gw1: { cpu: 52, mem: 50 } },
        log: { level: 'warn', text: 'GW-1: new-connection rate rising steadily.' } },
      { atSecond: 15, targets: { gw1: { cpu: 94, mem: 83 } },
        alert: { level: 'critical', device: 'gw1', title: 'GW-1: connection-tracking table near exhaustion', detail: 'An internal host is opening new connections at an unusually high rate; GW-1\'s session table is filling up, degrading forwarding for every device behind it.' },
        log: { level: 'err', text: 'ALERT: GW-1 CPU 94%, connection table 96% full — not an inbound flood.' } },
      { atSecond: 24, targets: { web1: { cpu: 42 } },
        links: [{ a:'web1', b:'wks2', latency: 150, loss: 2.0 }],
        alert: { level: 'warning', device: 'web1', title: 'WKS-02: connection churn straining shared services', detail: 'WKS-02\'s own bandwidth use looks normal, but the sheer rate of new connections it is opening is what is straining GW-1.' },
        log: { level: 'warn', text: 'WKS-02 identified as source of new-connection churn; ISP uplink traffic itself is not elevated.' } },
    ],
  },
  web_leak_incident: {
    packetPattern: 'webleak',
    focusDevice: 'web1',
    stages: [
      { atSecond: 0,  log: { level: 'info', text: 'Baseline monitoring active. All systems nominal.' } },
      { atSecond: 8,  targets: { web1: { mem: 70 } },
        log: { level: 'warn', text: 'SRV-WEB-1: memory usage climbing steadily, no corresponding traffic increase.' } },
      { atSecond: 18, targets: { web1: { mem: 96, cpu: 58 } },
        alert: { level: 'critical', device: 'web1', title: 'SRV-WEB-1: memory near exhaustion', detail: 'Memory has climbed continuously without leveling off — consistent with a memory leak. CPU is only now rising as the system begins swapping.' },
        log: { level: 'err', text: 'ALERT: SRV-WEB-1 memory 96% — swapping, worker processes slow to respond.' } },
      { atSecond: 27, targets: { web1: { cpu: 84 } },
        links: [{ a:'gw1', b:'web1', latency: 170, loss: 1.5 }],
        alert: { level: 'warning', device: 'web1', title: 'SRV-WEB-1: requests timing out', detail: 'Downstream clients are now seeing timeouts as the overloaded worker processes fail to keep up with the request queue.' },
        log: { level: 'warn', text: 'WKS-01 and WKS-02 report timeouts reaching SRV-WEB-1.' } },
    ],
  },
  loop_storm_incident: {
    packetPattern: 'loop',
    focusDevice: 'sw1',
    stages: [
      { atSecond: 0,  log: { level: 'info', text: 'Baseline monitoring active. All systems nominal.' } },
      { atSecond: 5,  targets: { sw1: { cpu: 55, traffic: 320 } },
        log: { level: 'warn', text: 'SW-1: broadcast traffic climbing — possible duplicate link forming a loop.' } },
      { atSecond: 13, targets: { sw1: { cpu: 97, traffic: 960 } },
        links: [{ a:'sw1', b:'wks1', latency: 220, loss: 6 }, { a:'sw1', b:'wks2', latency: 230, loss: 6.5 }, { a:'sw1', b:'wks3', latency: 210, loss: 5.5 }],
        alert: { level: 'critical', device: 'sw1', title: 'SW-1: broadcast storm detected', detail: 'Broadcast/multicast frames are being endlessly re-forwarded around a loop, consuming nearly all of SW-1\'s switching capacity.' },
        log: { level: 'err', text: 'ALERT: SW-1 traffic near link capacity — all attached workstations losing connectivity.' } },
      { atSecond: 22, log: { level: 'warn', text: 'GW-1 and SRV-WEB-1 (upstream of SW-1) remain unaffected — the storm is confined to the SW-1 LAN segment.' } },
    ],
  },
};

/* ─────────────────────────── LESSONS ─────────────────────────── */
export const LESSONS = [
  {
    id: 'ddos_edge',
    title: 'DDoS at the Edge',
    difficulty: 'Beginner',
    focus: 'Gateway / Router',
    accent: '#F59E0B',
    topology: 'branch_office',
    incident: 'ddos_incident',
    description: 'Users report the branch office site is unreachable and slow. Watch the network react and find the affected device.',
    objective: 'Traffic into the branch office has spiked and users report slow or failed connections. Determine what is happening and which device is affected.',
    diagQuestion: 'Based on the telemetry, topology, and packet evidence, what is the most likely root cause?',
    options: [
      { id: 'a', text: 'GW-1 is being overwhelmed by a traffic flood (DDoS) from many external sources.', correct: true },
      { id: 'b', text: 'SRV-DB-1 has run out of disk space.', correct: false },
      { id: 'c', text: 'A workstation NIC has failed.', correct: false },
      { id: 'd', text: 'This is normal end-of-month backup traffic and nothing is wrong.', correct: false },
    ],
    hints: [
      'Start on the Overview tab — which device shows the largest change in CPU and traffic once the simulation starts?',
      'Open Topology and watch link color between the ISP uplink and GW-1 as the incident develops.',
      'Check the Packets tab: do you see many different source addresses all hitting the same destination and port in a short window?',
    ],
    explanation: 'GW-1 received an abnormal surge of inbound connections from many distinct source addresses in a short window — a volumetric/SYN-style flood. That drove GW-1\'s CPU and uplink utilization to their limits, which is why packet loss and latency rose on the ISP link, and why SRV-WEB-1 then looked starved (it simply stopped receiving as much traffic, because it was stuck behind a congested gateway). The fix in the real world is upstream filtering/rate-limiting at the edge — not touching the web or database servers, which were never the actual problem.',
  },
  {
    id: 'db_slowdown',
    title: 'Runaway Database Query',
    difficulty: 'Intermediate',
    focus: 'Database Server',
    accent: '#A78BFA',
    topology: 'branch_office',
    incident: 'db_slowdown_incident',
    description: 'The web app feels sluggish for everyone. No obvious network flood this time — dig into the database tier.',
    objective: 'SRV-WEB-1 is responding slowly to all requests, but there is no unusual inbound traffic at the edge. Find the underlying cause.',
    diagQuestion: 'What is most likely causing the slow web responses?',
    options: [
      { id: 'a', text: 'SRV-DB-1 is disk-I/O bound from a heavy/long-running query, and SRV-WEB-1 is waiting on it.', correct: true },
      { id: 'b', text: 'GW-1 is under a DDoS attack.', correct: false },
      { id: 'c', text: 'WKS-03 is offline.', correct: false },
      { id: 'd', text: 'The ISP uplink has been disconnected.', correct: false },
    ],
    hints: [
      'The Gateway looks calm this time — traffic in is normal. Check Devices and compare CPU/disk across all servers, not just the gateway.',
      'Open Metrics and look at "Per-Device Snapshot" — which device has both high CPU and high disk I/O together?',
      'Look at the SRV-WEB-1 ↔ SRV-DB-1 link latency in Topology once the incident is underway.',
    ],
    explanation: 'SRV-DB-1 shows high CPU together with high disk I/O — the signature of a query doing heavy, repeated disk scans rather than a network problem. Because SRV-WEB-1 depends on SRV-DB-1 for every request, its response times rise in lockstep once the database falls behind, even though nothing at the network edge changed. The evidence chain (DB disk I/O → DB CPU → web↔db link latency → web app slowness) is what separates this from a network-layer incident like the DDoS lesson.',
  },
  {
    id: 'gpu_thermal',
    title: 'GPU Cluster Thermal Throttling',
    difficulty: 'Advanced',
    focus: 'AI / GPU Compute',
    accent: '#22C55E',
    topology: 'ai_cluster',
    incident: 'gpu_thermal_incident',
    description: 'One node in the training cluster is slowing everyone else down. Use monitoring to find which node, and why.',
    objective: 'A distributed training job across three GPU nodes has slowed down overall. One node is suspected. Identify it and explain the mechanism.',
    diagQuestion: 'What is happening to the affected GPU node, and why does it slow the whole job down?',
    options: [
      { id: 'a', text: 'GPU-NODE-02 overheated under sustained load and is now thermal-throttling, which stalls its sync traffic with the other nodes.', correct: true },
      { id: 'b', text: 'SRV-STORAGE has run out of disk space, stopping all checkpoints.', correct: false },
      { id: 'c', text: 'GW-1 is dropping all packets to the AI cluster.', correct: false },
      { id: 'd', text: 'GPU-NODE-02 is idle and simply not doing any work.', correct: false },
    ],
    hints: [
      'Compare the three GPU nodes on the Devices tab — GPU utilization alone won\'t tell the whole story, also check temperature.',
      'A node that throttles will show GPU load fall back down even though the job is not finished — check the trend, not just one snapshot.',
      'Check the link between SRV-SCHED and the affected node in Topology/Metrics for rising latency or loss once throttling kicks in.',
    ],
    explanation: 'GPU-NODE-02 ran at sustained near-100% GPU utilization long enough for its temperature to cross a safe threshold, triggering thermal throttling. Throttling forces the node to reduce clock speed, which cuts its effective throughput — visible as GPU utilization dropping back down even though the job isn\'t finished. Because distributed training nodes must synchronize with each other, the slow node\'s sync traffic to SRV-SCHED starts showing added latency/loss, and the whole job\'s pace drops to match its slowest member. This is a compute/thermal problem wearing a "network slowness" costume — the topology and link metrics are evidence of the cause, not the cause itself.',
  },
  {
    id: 'internal_overload',
    title: 'The Overload That Came From Inside',
    difficulty: 'Intermediate',
    focus: 'Gateway / Router',
    accent: '#EF4444',
    topology: 'branch_office',
    incident: 'internal_overload_incident',
    description: 'GW-1 is struggling again — but this time the WAN link looks calm. If it isn\'t a flood from outside, where is the load actually coming from?',
    objective: 'GW-1\'s CPU and memory are climbing even though inbound WAN traffic is normal. Determine whether this is an external attack or something originating inside the network.',
    diagQuestion: 'GW-1 is overloaded, but the ISP uplink shows no unusual traffic volume. What is the most likely explanation?',
    options: [
      { id: 'a', text: 'An internal host is opening new connections at an abnormally high rate, exhausting GW-1\'s connection-tracking table from the inside.', correct: true },
      { id: 'b', text: 'GW-1 is being hit by an external DDoS attack, identical to the branch office\'s earlier incident.', correct: false },
      { id: 'c', text: 'SRV-DB-1\'s disk has failed, forcing GW-1 to compensate.', correct: false },
      { id: 'd', text: 'The ISP has throttled the uplink bandwidth.', correct: false },
    ],
    hints: [
      'Compare this incident to the DDoS lesson: is the ISP-uplink link showing the same traffic spike this time?',
      'Open Packets — where is the flood of new connections actually coming from: outside addresses, or one particular internal device?',
      'A connection-tracking table can fill up from connection *count*, not just raw bandwidth — a device can overload a router without pushing much data at all.',
    ],
    explanation: 'Unlike the DDoS lesson, the ISP uplink here stays calm — inbound WAN traffic never spikes. The packet evidence instead shows WKS-02 opening an unusually high rate of new outbound connections. Each connection needs an entry in GW-1\'s connection-tracking (NAT) table, and enough of them opened fast enough exhausts that table regardless of how much actual data flows through it. That is why GW-1\'s CPU and memory climb while its traffic volume barely moves — a good reminder that "overloaded" and "flooded with bandwidth" are not the same thing, and that the fix here is investigating WKS-02, not the network edge.',
  },
  {
    id: 'web_leak',
    title: 'The Web Server That Forgot to Let Go',
    difficulty: 'Intermediate',
    focus: 'Web / App Server',
    accent: '#06B6D4',
    topology: 'branch_office',
    incident: 'web_leak_incident',
    description: 'SRV-WEB-1 gets slower and slower over several minutes with no traffic spike anywhere. Something on the server itself isn\'t releasing memory.',
    objective: 'SRV-WEB-1\'s response times are steadily degrading with no change in incoming traffic. Identify the resource that is failing and explain the order symptoms appeared in.',
    diagQuestion: 'Memory on SRV-WEB-1 rises continuously well before CPU or latency move at all. What does that ordering point to?',
    options: [
      { id: 'a', text: 'A memory leak in the web application — memory exhaustion forces swapping, which is what eventually drags CPU and response time down with it.', correct: true },
      { id: 'b', text: 'SRV-DB-1 is under heavy disk I/O load.', correct: false },
      { id: 'c', text: 'GW-1 is being flooded with inbound traffic.', correct: false },
      { id: 'd', text: 'WKS-01 has a failing network cable.', correct: false },
    ],
    hints: [
      'Check the Overview traffic chart for SRV-WEB-1 — has inbound traffic actually changed at all during the incident?',
      'On the Devices tab, watch the order metrics change: which one moves first, memory or CPU?',
      'Once a system\'s memory is exhausted it starts swapping to disk — what does that do to CPU usage and response latency?',
    ],
    explanation: 'The timeline is the evidence: SRV-WEB-1\'s memory climbs steadily from early in the incident while traffic stays flat and CPU barely moves — ruling out a network or load-driven cause. Only once memory is nearly exhausted does CPU start climbing too, because the system has begun swapping memory to disk, which is slow and CPU-intensive. Response times then degrade for everyone downstream (WKS-01, WKS-02) purely as a consequence of that swapping, not because of anything happening on the network. That memory-first, CPU-and-latency-second ordering is the signature of an application-level memory leak, distinct from the disk-I/O-driven database incident elsewhere in this trainer.',
  },
  {
    id: 'loop_storm',
    title: 'Broadcast Storm on the LAN',
    difficulty: 'Beginner',
    focus: 'Switch',
    accent: '#38BDF8',
    topology: 'small_lan',
    incident: 'loop_storm_incident',
    description: 'Every workstation on one switch suddenly loses its connection at the same time, while the router and web server upstream look completely fine.',
    objective: 'WKS-01, WKS-02, and WKS-03 all degrade at once while GW-1 and SRV-WEB-1 stay healthy. Localize the fault to the correct layer of the network.',
    diagQuestion: 'All three workstations behind SW-1 degrade simultaneously, while GW-1 and SRV-WEB-1 — both upstream of SW-1 — stay perfectly healthy. What does this pattern indicate?',
    options: [
      { id: 'a', text: 'SW-1 is experiencing a broadcast storm, likely from a switching loop, flooding the LAN segment behind it while everything upstream is unaffected.', correct: true },
      { id: 'b', text: 'GW-1 has lost its connection to the ISP.', correct: false },
      { id: 'c', text: 'SRV-WEB-1 has crashed.', correct: false },
      { id: 'd', text: 'All three workstations independently developed hardware faults at the same moment.', correct: false },
    ],
    hints: [
      'Three unrelated devices failing at the exact same instant is unlikely to be three coincidental hardware faults — look for a shared point they all pass through.',
      'Check SW-1\'s own CPU and traffic on the Devices tab — how do they compare to GW-1 and SRV-WEB-1, which sit one hop further upstream?',
      'Open Packets: repeated broadcast frames and Spanning Tree Protocol topology-change notifications are the classic signature of a network loop.',
    ],
    explanation: 'SW-1 sits directly between the three workstations and the rest of the network, and it is the only device whose traffic and CPU spike toward their limits — a broadcast storm, almost certainly caused by a physical loop (two cables connecting the same two switches/ports without loop protection). Broadcast frames get endlessly duplicated and re-forwarded around the loop, consuming nearly all of SW-1\'s switching capacity and starving every port behind it — which is exactly why all three workstations degrade at once. GW-1 and SRV-WEB-1 sit one hop further upstream, on the other side of SW-1, so they never see the storm. Three devices failing in perfect unison is a strong clue to look for a shared upstream device rather than three independent faults, and the packet evidence (repeated broadcasts, STP topology-change notifications) confirms a Layer-2 loop rather than a routing or server problem.',
  },
];
